#!/bin/sh

case "$(uname -s)" in
  Darwin)

    ./.dotbot/install-mac
    ;;

  Linux)
    if [ "$SPIN" ]
    then
      # ./.dotbot/install-ubuntu
    else
      ./.dotbot/install-arch
    fi
    ;;

  *)
    echo 'Not supported OS'
    ;;
esac
