- link:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/aliases.fish: fish/aliases.fish
    ~/.config/fish/fish_plugins: fish/fish_plugins
    ~/.config/fish/functions: fish/functions
    ~/.config/fish/plugins: fish/plugins
