- yay:
  - alacritty
  - bat
  - binutils
  - cmake
  - coreutils
  - docker
  - docker-compose
  - exa
  - fakeroot
  - fd
  - firefox-developer-edition
  - fish
  - fzf
  - git-delta
  - htop
  - httpie
  - hub
  - jq
  - matcha-gtk-theme
  - neovim
  - noto-fonts-emoji
  - pv
  - ripgrep
  - rsync
  - slack-desktop
  - spotify
  - synology-drive
  - tmux
  - translate-shell
  - yay
  - youtube-dl

