alias ls 'exa -a'
alias cat 'bat'
alias vim 'nvim'
alias reload! 'source ~/.config/fish/config.fish'
alias gapan 'git add --intent-to-add . && git add --patch'
alias git-branch-fzf "git branch -vv --color=always | fzf-tmux -d 15 --ansi | cut -c3- | cut -d' ' -f1"
alias gcob 'git checkout (git-branch-fzf)'
alias gcmsg 'git commit -m'
alias gundo='git reset HEAD~'
alias gundo='git reset HEAD~'
alias t='trans'
alias :q='exit'
alias dco 'docker-compose'
alias dce 'docker-compose exec'
alias dl 'docker ps -l -q'
alias dbe 'docker-compose run rails env bundle exec'
alias speedtest-bytes 'wget -O /dev/null http://speedtest.tele2.net/10GB.zip'
alias speedtest-bits 'wget -O /dev/null http://speedtest.tele2.net/10GB.zip --report-speed=bits'

# MAC
alias cpu_temp 'sudo powermetrics --samplers smc |grep -i "CPU die temperature"'
